name: Build and Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.DOCKER_IMAGE_REGISTRY_URL }}
            username: ${{ secrets.DOCKER_IMAGE_REGISTRY_USERNAME }}
            password: ${{ secrets.DOCKER_IMAGE_REGISTRY_PASSWORD }}

        - name: Extract version
          shell: bash
          run: echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_IMAGE_REGISTRY_URL }}/mqtt-forwarder:1.${{ env.VERSION }}  # replace 'your_username/your_repository' with your GitHub username and repository
            build-args: |
                VERSION: ${{ env.VERSION }}
